baseURL = "https://peterwright95.github.io/SDA"
languageCode = "en-us"
title = "SDA Project - Taxi Dataset"
theme = "ananke"
publishDir = "docs"
[markup.goldmark.renderer]
    unsafe = true
[params]
   custom_css = ["css/w3.css"]